#
##Service monitor for prometheus operator
#apiVersion: monitoring.coreos.com/v1
#kind: ServiceMonitor
#metadata:
#  labels:
#    app: prometheus-example-app
#  name: prometheus-example-monitor
#  namespace: default
#spec:
#  endpoints:
#  - path: /metrics
#    port: web
#    scheme: http
#  #This is selector for SERVICE objects
#  selector:
#    matchLabels:
#      app: prometheus-example-app
#
#---
##Grafana Dashboard ConfigMap
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  labels:
#    grafana_dashboard: "1"
#  name: example-dashboard
#  namespace: default
#data:
#  example-dashboard.json: |-
#    {
#    ....
#    }
#
#---
##AlertTule for prometheus
#apiVersion: monitoring.coreos.com/v1
#kind: PrometheusRule
#metadata:
#  name: example-alert
#  namespace: default
#  labels:
#    role: alert-rules
#spec:
#  groups:
#  - name: example
#    rules:
#    - alert: VersionAlert
#      #Генерировать алерт если указанное выражение возвращает значения более 10 минут подряд. Отправлять алерт в Alertmanager.
#      for: 10m
#      expr: version{job="prometheus-example-app"} == 1
#      #В лейблах и аннотациях можно использовать синтаксис темплейтинга и ссылаться на имеющиеся лейблы метрик, вернувшихся из expr.
#      #При отправке в Alertmanager лейблы указанные ниже будут объединены с имеющимися лейблами метрик вернувшихся из expr. По лейблам доступны фильтрация, группировка и роутинг в Alertmanager.
#      #Стандартный шаблон e-mail в Alertmanager вставляет в оповещение все имеющиеся лейблы и аннотации.
#      labels:
#          #severity нужно заполнять. Варианты - info|warning|critical
#          severity: warning
#          example_label: "{{ $labels.namespace }}"
#      annotations:
#          description: "Just a Warning. {{ $labels.instance }} of job {{ $labels.job }}"
#      #В одном PrometheusRule может быть несколько алертов. У алертов могут быть одинаковые имена но, например, разные severity.
#    - alert: VersionAlert
#      for: 10m
#      expr: version{job="prometheus-example-app"} == 1
#      labels:
#          severity: critical
#          example_label: "{{ $labels.namespace }}"
#      annotations:
#          description: "Critical Alert. {{ $labels.instance }} of job {{ $labels.job }}"