resources:
  - ../base

namespace: production

patchesJSON6902:
- target:
    kind: Ingress
    name: vaadin-demo-bakery-app
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: bakery.smolkov.spb.ru
    - op: replace
      path: /spec/tls/0/hosts/0
      value: bakery.smolkov.spb.ru
    - op: replace
      path: /spec/tls/0/secretName
      value: bakery-tls