apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: vaadin-demo-bakery-app
  name: vaadin-demo-bakery-app
  namespace: dummy
spec:
  endpoints:
  - path: /actuator/prometheus
    port: http
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: vaadin-demo-bakery-app