spring:
  application:
    name: ${APP_NAME:vaadin-demo-bakery-app}
management:
  security:
    enabled: false
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}