name: Deploy (staging/production)
on:
  workflow_dispatch:
    inputs:
      deployVersion:
        description: Docker image to deploy
        required: true

jobs:
  deploy-staging:
    permissions: read-all
    uses: ./.github/workflows/deploy_reusable_workflow.yml
    with:
      deployVersion: ${{ github.event.inputs.deployVersion }}
      environment: staging
      environment_url: https://bakery-staging.smolkov.spb.ru
    secrets: inherit

  deploy-production:
    needs: deploy-staging
    permissions: read-all
    uses: ./.github/workflows/deploy_reusable_workflow.yml
    with:
      deployVersion: ${{ github.event.inputs.deployVersion }}
      environment: production
      environment_url: https://bakery.smolkov.spb.ru
    secrets: inherit