name: Deploy application
on:
  workflow_dispatch:
    inputs:
      deployVersion:
        description: Docker tag to deploy
        required: true


jobs:
  deploy-develop:
    uses: ./.github/workflows/deploy_reusable_workflow.yml
    with:
      deployVersion: ${{ github.event.inputs.deployVersion }}
      environment: develop
    secrets: inherit
