name: Perform deploy
on:
  workflow_dispatch:
    inputs:
      deployVersion:
        description: Docker tag to deploy
        required: true
env:
  APP_NAME: vaadin-demo-bakery-app

jobs:
  deploy:
    name: Deploy project
    runs-on: ubuntu-20.04
    permissions: read-all
    steps:
      - name: check tag existance
        id: check_existence
        run: |  
          REPOSITORY_ID=$(echo ${{ github.repository_owner }}/${APP_NAME}  | tr '[A-Z]' '[a-z]')
          IMAGE_ID=$(echo ghcr.io/${REPOSITORY_ID}| tr '[A-Z]' '[a-z]')
          VERSION=$(echo ${{ github.event.inputs.deployVersion }} | tr '[A-Z]' '[a-z]')
          REPOSITORY_TOKEN=$(curl -u ${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }} https://ghcr.io/token\?scope\="repository:${REPOSITORY_ID}:pull" | jq -r .token)
          
          echo https://ghcr.io/v2/${IMAGE_ID}/manifests/${VERSION}
          curl --head --fail -H "Authorization: Bearer ${REPOSITORY_TOKEN}" https://ghcr.io/v2/${IMAGE_ID}/manifests/${VERSION}
