name: Deploy application (staging/production)
on:
  workflow_dispatch:
    inputs:
      deployVersion:
        description: Docker image to deploy
        required: true

  deploy-staging:
    permissions: read-all
    uses: ./.github/workflows/reusable/deploy_reusable_workflow.yml
    with:
      deployVersion: ${{ github.event.inputs.deployVersion }}
      environment: staging
    secrets: inherit

  deploy-production:
    needs: deploy-staging
    permissions: read-all
    uses: ./.github/workflows/reusable/deploy_reusable_workflow.yml
    with:
      deployVersion: ${{ github.event.inputs.deployVersion }}
      environment: production
    secrets: inherit