name: Deploy application
on:
  workflow_dispatch:
    inputs:
      deployVersion:
        description: Docker tag to deploy
        required: true


jobs:
  deploy-develop:
    uses: ./.github/workflows/deploy_reusable_workflow.yml
    with:
      username: mona
      secrets: inherit
    name: Deploy project to develop env
    environment: 
      name: develop
      url: https://bakery-develop.smolkov.spb.ru 
    env:
      ENVIRONMENT: develop
    runs-on: ubuntu-20.04
    permissions: read-all
