name: Build Project New

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
    tags:        
      - v**
env:
  DOCKER_IMAGE_ID: ghcr.io/${{ github.repository_owner }}/vaadin-demo-bakery-app

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-20.04
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0                # fetch the whole repo history

    - name: Git Version
      id: version
      run:  iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/AntonSmolkov/HandyPoshScripts/github-action/DevOps/SemVerCalc_GitHubFlow_Actions.ps1'))
      shell: pwsh
      env:
        REF_NAME: ${{ github.ref_name }}
        REF_TYPE: ${{ github.ref_type }}

    - uses: actions/setup-java@v3
      name: Install JDK
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    - uses: actions/setup-node@v3
      name: Install NodeJS
      with:
       node-version: 14
       cache: 'npm'
 
    - name: Compile
      run: mvn clean compile test-compile -Pproduction

    - name: Test
      run: mvn surefire:test || exit 0

    - name: Generate test report
      uses: mikepenz/action-junit-report@v3.0.3
      with:
         report_paths: '**target/surefire-reports/TEST-*.xml'
         fail_on_failure: true
         include_passed: true

    - name: Package
      run: mvn jar:jar -Drevision=${VERSION}
      env:
        VERSION: ${{ steps.version.outputs.calculated_version }}

    - name: Build image
      run: docker build . --file Dockerfile --tag ${DOCKER_IMAGE_ID}:${VERSION} --label "runnumber=${GITHUB_RUN_ID}"
      env:
        VERSION: ${{ steps.version.outputs.calculated_version }}

    - name: Log in to docker registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Push image to docker registry
      run: |
        docker push ${DOCKER_IMAGE_ID}:${VERSION}
        if [[ "${IS_RELEASE}" == "true" ]]
        then
          docker tag ${DOCKER_IMAGE_ID}:${VERSION} ${DOCKER_IMAGE_ID}:latest
          docker push $IMAGE_ID:latest
        fi
      env:
        VERSION: ${{ steps.version.outputs.calculated_version }}
        IS_RELEASE: ${{ steps.version.outputs.calculated_version_is_release }}
