name: Build Project New

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
    tags:        
      - v**

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-20.04
    steps:
    
    - uses: actions/checkout@v3
    
    - uses: actions/setup-java@v3
      name: Install JDK
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    - uses: actions/setup-node@v3
      name: Install NodeJS
      with:
       node-version: 14
       cache: 'npm'
 
    - name: Compile
      run: mvn clean compile --file pom.xml

    - name: Test
      run: mvn surefire:test --file pom.xml

    - name: Generate test report
      uses: mikepenz/action-junit-report@v3.0.3
      if: always() # always run even if the previous step fails
      with:
         report_paths: '**target/surefire-reports/TEST-*.xml'
         fail_on_failure: true
         include_passed: true

    - name: Package
      run: mvn jar:jar --file pom.xml
