name: Perform Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Release Version
        required: true

env:
  IMAGE_NAME: vaadin-demo-bakery-app
  IMAGE_TAG:  ${{ github.event.inputs.releaseVersion }}

jobs:
  tag_release:
    name: Tag Release
    runs-on: ubuntu-latest
    permissions: 'read-all|write-all'
    steps:
      - name: Check out project
        uses: actions/checkout@v2

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Git tag release
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.releaseVersion }}

#   docker_image:
#     name: Docker Image
#     runs-on: ubuntu-latest
#     needs: [ tag_release ]

#     steps:
#       - uses: actions/checkout@v2
#         with:
#           ref: ${{ github.event.inputs.releaseVersion }}

#       - name: Build image
#         run: |
#           docker build . --file Dockerfile --tag $IMAGE_NAME:$IMAGE_TAG
#           docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest

#       - name: Log into registry
#         run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

#       - name: Push image
#         run: |
#           docker push $IMAGE_NAME:$IMAGE_TAG
#           docker push $IMAGE_NAME:latest


  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:IMAGE_TAG --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:IMAGE_TAG
          docker push $IMAGE_NAME:IMAGE_TAG
